site_name: ConcursoFácil Docs

repo_name: "concursofacil-docs"
repo_url: "https://github.com/ConcursoFacil/concursofacil-docs"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top  
  palette:
    primary: blue
    accent: blue

nav:
  - Página Inicial: index.md
  - Visão do Produto: produto/visao.md
  - Requisitos:
    - Requisitos de Software: requisitos/requisitos.md
    - Backlog: requisitos/backlog.md
    - Histórias de Usuário: requisitos/user_stories.md
  - Arquitetura:
    - Arquitetura: arquitetura/arquitetura.md
    - UML: arquitetura/uml.md
    - Banco: arquitetura/banco.md
  - Protótipo: prototipo/prototipo.md

plugins:
  - search
  - glightbox
  - mermaid2     # ✔️ plugin certo

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js   # ✔️ necessário para GitHub Pages

extra:
  mermaid2:
    arguments:
      theme: neutral
